version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lerka-backend
    env_file:
      - .env
    depends_on:
      - ollama
    networks:
      - lerka-network

  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    container_name: lerka-ollama
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - lerka-network

networks:
  lerka-network:
    driver: bridge

volumes:
  ollama_data:
